### ISSUE TITLE
[solved] Error vesamenu.c32

### ISSUE THREAD

**Issue by jlmurillo** [chamuco/respin#13]
Ubuntu 15.04 + usb-creator-gtk iso created with remastersys she gives the following errors:

```
    Failed to load COM32 file vesamenu.c32
    boot:
```

Or

```
    failed to load libcom32.c32
    failed to load COM32 file libcom32.c32
    boot:
```

and do not run

To fix this from remastersys in usr/bin/remastersys.bin I've changed: 

after

```
    cp $VESAMENU $WORKDIR/ISOTMP/isolinux/ 
```

I have added

```
cp /usr/lib/syslinux/modules/bios/libcom32.c32 $WORKDIR/ISOTMP/isolinux/ 
cp /usr/lib/syslinux/modules/bios/libutil.c32 $WORKDIR/ISOTMP/isolinux/
```

And perfect boot iso creating remastersys+ubuntu 15.04 + desktop MATE+usb-creator-gtk 

I hope that also serve this track for Respin ;-)

Note: I've put the path to the files as they are in Ubuntu 15.04 because I do not know how to write it so that it fits all ubuntus. I leave it to you change it ;-) I will say.

**Comment by repsol** [comment]
That is great information that you very much for your help.
