### ISSUE TITLE
ISO booting problems. 

### ISSUE THREAD

**Issue by Zekodon** [chamuco/respin#21]
The iso and md5 files appear in the filesystem where they are (all very well and good) but when I try to boot the iso into a VM it just doesn't boot. Why is this, and is there anything I'm doing wrong?

**Comment by ch1x0r** [comment]
I believe one of our team statee he had the same issue in a vm with Ubuntu. Have you tried using the live outside a vm... Ubuntu Guys? What was the vm issue...wait. Is it because mkisofs? Is this version current?

**Comment by repsol** [comment]
There could be several factors but the number one is the the ISO can't be
more than 4G. We will need more info to help. The issue that I had was not
being able to log into live in Virtualbox, but it worked in KVM. There is
some bug with the live and virtualbox but the backup worked fine.

What OS and window manager are you using?

Also is this the Debian Version or the Ubuntu version?

Cheers,
Adrenaline

**Comment by Zekodon** [comment]
EDIT: Also, the iso file was no larger than 2GB, so I think that's out of the question.

I'm using Linux mint 17.3, and because Linux Mint is based off of ubuntu I downloaded the 'ubuntu' version of respin. The VM I tested this on was a Virtualbox VM on a windows 8.1 PC. 

When I made the iso file, I used the 'dis' button with fiddling with any of the other settings on that page. 
Was this info helpful? I'd be great if this helps solve the issue! :-)

**Comment by repsol** [comment]
Hi Zekodon,

It is helpful,

Even though Mint is based on Ubuntu, it uses it's own proprietary display
manager, where as Ubuntu uses lightdm.

What happens is it breaks the log-in on the "dist" install. If you do a
backup, it grabs the login from your host machine, but in the dist mode it
breaks.

I hope that makes sense, we have not found a work around for dist Mint yet,
but run it again, but this time do a "backup" and I think it will work for
you.

Let us know if you run into any more issues,

Cheers,
Adrenaline

**Comment by Zekodon** [comment]
Alright! I got it to boot into the installer! I used the "backup" button and it made the iso bootable. The Problem now it that when the dialogue appears and I boot directly into the installer, it works fine. However, when I boot into the live session, the live session user can't sign in.
Is it because I made a blank dummy account and told respin to use the blank account as the template account?Should I have left it blank?

**Comment by repsol** [comment]
Nope that is the bug. It is because Mint doesn't use Lightdm. Mint uses
MDM, and we have not found a workaround yet. We have some people working on
it, but no dice yet. I have tried to add a shadow file which did indeed
work, but when the isofs was made it over wrote the file. I know we are
close, but not quite there yet.

**Comment by Zekodon** [comment]
Can you let me know when you find that workaround?

**Comment by ch1x0r** [comment]
I have totally got this to work with mint. https://github.com/ch1x0r/MintyFresh2016/tree/master/respinminty_1.0.0-1_all

**Comment by ch1x0r** [comment]
Ok...it says deb...but it really is mint.... 

https://github.com/ch1x0r/MintyFresh2016?files=1

**Comment by Zekodon** [comment]
I'll try that out when I get the chance, thank you.
